### ISSUE TITLE
Update Testsuite to Neo 5.2.0.

### ISSUE THREAD

**Issue by wurzelkuchen** [Xceptance/neodymium-example#29]
## Quick Description ##

Since we soon roll out neo 5.2.0. please update this testsuite to the new version. Be aware that this version is not yet public in maven, so for test purposes you have to build it locally.

## Tasks ##

- [ ] update pom to version 5.2.
- [ ] add new properties  to neodymium.properties
- [ ] add new features to existing testcases where it is useful. E.g. we could add the seperate browser for cleanup feature, to one of the testcases which needs a cleanup

**Comment by RobertAvemarg** [comment]
Since we need a new Neodymium release to fix the problem with the Cucumber version, I'll wait until it's released and update directly to that release.

**Comment by wurzelkuchen** [comment]
officially changed version number to next neo version
